version: "3"

services:
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./tmp/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel-websockets
            MYSQL_ROOT_PASSWORD: root
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
